package com.takima.adsample.persistance;

public enum Rules {
	RULE_FIRST_NAME_LENGTH,
	RULE_LAST_NAME_LENGTH,
	RULE_EMAIL_ALPHA_RATE,
	RULE_EMAIL_NUM_RATE,
	RULE_PRICE_QUOTATION_RATE,
	RULE_REGISTER_NUMBER_BLACKLIST
}
